<?php

return [

    'US' => [
        'name' => 'United States',
        'postal_code_label' => 'ZIP Code',
        'postal_code_format' => '/^\d{5}(-\d{4})?$/',
        'postal_code_required' => true,
        'administrative_area_label' => 'State',
        'administrative_area_required' => true,
        'administrative_area_options' => [
            'AL' => 'Alabama', 'AK' => 'Alaska', 'AZ' => 'Arizona', 'AR' => 'Arkansas',
            'CA' => 'California', 'CO' => 'Colorado', 'CT' => 'Connecticut',
            'DC' => 'District of Columbia', 'DE' => 'Delaware', 'FL' => 'Florida',
            'GA' => 'Georgia', 'HI' => 'Hawaii', 'ID' => 'Idaho', 'IL' => 'Illinois',
            'IN' => 'Indiana', 'IA' => 'Iowa', 'KS' => 'Kansas', 'KY' => 'Kentucky',
            'LA' => 'Louisiana', 'ME' => 'Maine', 'MD' => 'Maryland',
            'MA' => 'Massachusetts', 'MI' => 'Michigan', 'MN' => 'Minnesota',
            'MS' => 'Mississippi', 'MO' => 'Missouri', 'MT' => 'Montana',
            'NE' => 'Nebraska', 'NV' => 'Nevada', 'NH' => 'New Hampshire',
            'NJ' => 'New Jersey', 'NM' => 'New Mexico', 'NY' => 'New York',
            'NC' => 'North Carolina', 'ND' => 'North Dakota', 'OH' => 'Ohio',
            'OK' => 'Oklahoma', 'OR' => 'Oregon', 'PA' => 'Pennsylvania',
            'RI' => 'Rhode Island', 'SC' => 'South Carolina', 'SD' => 'South Dakota',
            'TN' => 'Tennessee', 'TX' => 'Texas', 'UT' => 'Utah', 'VT' => 'Vermont',
            'VA' => 'Virginia', 'WA' => 'Washington', 'WV' => 'West Virginia',
            'WI' => 'Wisconsin', 'WY' => 'Wyoming',
        ],
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'CA' => [
        'name' => 'Canada',
        'postal_code_label' => 'Postal Code',
        'postal_code_format' => '/^[A-Z]\d[A-Z]\s?\d[A-Z]\d$/i',
        'postal_code_required' => true,
        'administrative_area_label' => 'Province',
        'administrative_area_required' => true,
        'administrative_area_options' => [
            'AB' => 'Alberta', 'BC' => 'British Columbia', 'MB' => 'Manitoba',
            'NB' => 'New Brunswick', 'NL' => 'Newfoundland and Labrador',
            'NS' => 'Nova Scotia', 'NT' => 'Northwest Territories',
            'NU' => 'Nunavut', 'ON' => 'Ontario', 'PE' => 'Prince Edward Island',
            'QC' => 'Quebec', 'SK' => 'Saskatchewan', 'YT' => 'Yukon',
        ],
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'GB' => [
        'name' => 'United Kingdom',
        'postal_code_label' => 'Postcode',
        'postal_code_format' => '/^[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}$/i',
        'postal_code_required' => true,
        'administrative_area_label' => 'County',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'Town / City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'AU' => [
        'name' => 'Australia',
        'postal_code_label' => 'Postcode',
        'postal_code_format' => '/^\d{4}$/',
        'postal_code_required' => true,
        'administrative_area_label' => 'State / Territory',
        'administrative_area_required' => true,
        'administrative_area_options' => [
            'ACT' => 'Australian Capital Territory', 'NSW' => 'New South Wales',
            'NT' => 'Northern Territory', 'QLD' => 'Queensland',
            'SA' => 'South Australia', 'TAS' => 'Tasmania',
            'VIC' => 'Victoria', 'WA' => 'Western Australia',
        ],
        'locality_label' => 'Suburb / City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'DE' => [
        'name' => 'Germany',
        'postal_code_label' => 'PLZ (Postleitzahl)',
        'postal_code_format' => '/^\d{5}$/',
        'postal_code_required' => true,
        'administrative_area_label' => 'State (Bundesland)',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'postal_code', 'locality'],
    ],

    'FR' => [
        'name' => 'France',
        'postal_code_label' => 'Code postal',
        'postal_code_format' => '/^\d{5}$/',
        'postal_code_required' => true,
        'administrative_area_label' => 'Region',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => true,
        'format' => ['address_line_1', 'address_line_2', 'postal_code', 'locality', 'sorting_code'],
    ],

    'JP' => [
        'name' => 'Japan',
        'postal_code_label' => '郵便番号 (Postal Code)',
        'postal_code_format' => '/^\d{3}-?\d{4}$/',
        'postal_code_required' => true,
        'administrative_area_label' => 'Prefecture',
        'administrative_area_required' => true,
        'administrative_area_options' => [
            '01' => 'Hokkaido',  '02' => 'Aomori',    '03' => 'Iwate',
            '04' => 'Miyagi',    '05' => 'Akita',     '06' => 'Yamagata',
            '07' => 'Fukushima', '08' => 'Ibaraki',   '09' => 'Tochigi',
            '10' => 'Gunma',     '11' => 'Saitama',   '12' => 'Chiba',
            '13' => 'Tokyo',     '14' => 'Kanagawa',  '15' => 'Niigata',
            '16' => 'Toyama',    '17' => 'Ishikawa',  '18' => 'Fukui',
            '19' => 'Yamanashi', '20' => 'Nagano',    '22' => 'Shizuoka',
            '23' => 'Aichi',     '24' => 'Mie',       '25' => 'Shiga',
            '26' => 'Kyoto',     '27' => 'Osaka',     '28' => 'Hyogo',
            '29' => 'Nara',      '30' => 'Wakayama',  '31' => 'Tottori',
            '32' => 'Shimane',   '33' => 'Okayama',   '34' => 'Hiroshima',
            '35' => 'Yamaguchi', '36' => 'Tokushima', '37' => 'Kagawa',
            '38' => 'Ehime',     '39' => 'Kochi',     '40' => 'Fukuoka',
            '41' => 'Saga',      '42' => 'Nagasaki',  '43' => 'Kumamoto',
            '44' => 'Oita',      '45' => 'Miyazaki',  '46' => 'Kagoshima',
            '47' => 'Okinawa',
        ],
        'locality_label' => 'City / Ward',
        'locality_required' => true,
        'dependent_locality_label' => 'District / Block',
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['postal_code', 'administrative_area', 'locality', 'dependent_locality', 'address_line_1', 'address_line_2'],
    ],

    'NZ' => [
        'name' => 'New Zealand',
        'postal_code_label' => 'Postcode',
        'postal_code_format' => '/^\d{4}$/',
        'postal_code_required' => true,
        'administrative_area_label' => 'Region',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'Suburb / City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'postal_code'],
    ],

    'MX' => [
        'name' => 'Mexico',
        'postal_code_label' => 'Código Postal',
        'postal_code_format' => '/^\d{5}$/',
        'postal_code_required' => true,
        'administrative_area_label' => 'State',
        'administrative_area_required' => true,
        'administrative_area_options' => [
            'AGU' => 'Aguascalientes', 'BCN' => 'Baja California',
            'BCS' => 'Baja California Sur', 'CAM' => 'Campeche',
            'CHP' => 'Chiapas', 'CHH' => 'Chihuahua',
            'CMX' => 'Ciudad de México', 'COA' => 'Coahuila de Zaragoza',
            'COL' => 'Colima', 'DUR' => 'Durango',
            'GUA' => 'Guanajuato', 'GRO' => 'Guerrero',
            'HID' => 'Hidalgo', 'JAL' => 'Jalisco',
            'MEX' => 'México', 'MIC' => 'Michoacán de Ocampo',
            'MOR' => 'Morelos', 'NAY' => 'Nayarit',
            'NLE' => 'Nuevo León', 'OAX' => 'Oaxaca',
            'PUE' => 'Puebla', 'QUE' => 'Querétaro',
            'ROO' => 'Quintana Roo', 'SLP' => 'San Luis Potosí',
            'SIN' => 'Sinaloa', 'SON' => 'Sonora',
            'TAB' => 'Tabasco', 'TAM' => 'Tamaulipas',
            'TLA' => 'Tlaxcala', 'VER' => 'Veracruz de Ignacio de la Llave',
            'YUC' => 'Yucatán', 'ZAC' => 'Zacatecas',
        ],
        'locality_label' => 'City / Municipality',
        'locality_required' => true,
        'dependent_locality_label' => 'Colonia / Neighborhood',
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'dependent_locality', 'locality', 'administrative_area', 'postal_code'],
    ],

    // ── Free-text fallback countries ────────────────────────────────────────────

    'BR' => [
        'name' => 'Brazil',
        'postal_code_label' => 'CEP',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'Estado',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'IN' => [
        'name' => 'India',
        'postal_code_label' => 'PIN Code',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'State',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'ZA' => [
        'name' => 'South Africa',
        'postal_code_label' => 'Postal Code',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'Province',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'NG' => [
        'name' => 'Nigeria',
        'postal_code_label' => 'Postal Code',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'State',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'KR' => [
        'name' => 'South Korea',
        'postal_code_label' => 'Postal Code',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'Province / City',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City / District',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'administrative_area', 'postal_code'],
    ],

    'IT' => [
        'name' => 'Italy',
        'postal_code_label' => 'CAP',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'Province',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'postal_code', 'locality', 'administrative_area'],
    ],

    'ES' => [
        'name' => 'Spain',
        'postal_code_label' => 'Código Postal',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'Province',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'postal_code', 'locality', 'administrative_area'],
    ],

    'NL' => [
        'name' => 'Netherlands',
        'postal_code_label' => 'Postcode',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'Province',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'postal_code', 'locality'],
    ],

    'SE' => [
        'name' => 'Sweden',
        'postal_code_label' => 'Postnummer',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'County',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'postal_code', 'locality'],
    ],

    'PT' => [
        'name' => 'Portugal',
        'postal_code_label' => 'Código Postal',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'District',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'postal_code', 'locality'],
    ],

    'SG' => [
        'name' => 'Singapore',
        'postal_code_label' => 'Postal Code',
        'postal_code_format' => null,
        'postal_code_required' => false,
        'administrative_area_label' => 'Region',
        'administrative_area_required' => false,
        'administrative_area_options' => null,
        'locality_label' => 'City',
        'locality_required' => true,
        'dependent_locality_label' => null,
        'address_line_3_used' => false,
        'sorting_code_used' => false,
        'format' => ['address_line_1', 'address_line_2', 'locality', 'postal_code'],
    ],

];
